### ISSUE TITLE
Invalid regex for checking twitter handles

### ISSUE THREAD

**Issue by raylee** [cbrgm/go-t#1]
Twitter handles can start with a digit (I'm @4raylee), so the following regex should be adjusted:

https://github.com/cbrgm/go-t/blob/c3a468271ed18a2fb460a5f715a764c799bb6718/pkg/config/config.go#L162

Thanks for the nifty tool, I'm looking forward to trying it out!

**Comment by cbrgm** [comment]
Fixed and merged into master. 
Thanks for your kind feedback and opening up the issue! 

Cheers
