### ISSUE TITLE
See notifications ?

### ISSUE THREAD

**Issue by edi0th** [cbrgm/go-t#7]
Hey ! I've strated using your twitter go app, and i have a a questions : ) Is it possible to see my notifications ? I can't find it in the doc.

Thanks for your work !

**Comment by cbrgm** [comment]
Hey @edi0th ! I think you mean by notifications whether someone mentioned you or retweetet something? 
You can use `t timeline [mentions/retweets]` to see if there is anything new. 

What there isn't, however, is something like a collected list of both. Maybe that would be something for a new feature, but that's not possible at the moment.

Cheers!

**Comment by edi0th** [comment]
Yes, sorry it wasn't very clear, but your partially answered. 
When i'm on the «ringbell» tab on twitter website, the list shows me a collected list of :
Tweets I made people liked, Tweets where I'm mentionned, Rewteets and new people who just followed me.
But with you answer, i understand it'es not possible at the moment : )
